import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import backgroundTexture from "@/assets/bg-texture.png"; // Import the texture image

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center bg-cover bg-no-repeat bg-center ${inter.className}`}
        style={{ backgroundImage: `url(${backgroundTexture.src})`, width: "100vw", height: "100vh" }}
      >
        {children}
      </body>
    </html>
  );
}
