import type { Metadata } from "next";
import "../globals.css";
import backgroundTexture from "@/assets/bg-texture.png";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center bg-cover bg-no-repeat bg-center`}
        style={{ backgroundImage: `url(${backgroundTexture.src})`, width: "100vw", height: "100vh" }}
      >
        {children}
      </body>
    </html>
  );
}
